name: Deploy Helper

on:
  push:
    branches:
      - main

jobs:
  split_nx_projects:
    runs-on: ubuntu-latest
    outputs:
      project_list: ${{ steps.set_up_matrix.outputs.project_list }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: setSHAs
        uses: nrwl/nx-set-shas@v4

      - name: Run color
        id: selectesed_colors
        run: echo "SELECTED_COLOR=green" >> "$GITHUB_OUTPUT"

      - name: Get color
        env:
          SELECTED_COLOR: ${{ steps.selectesed_colors.outputs.SELECTED_COLOR }}
        run: echo "The selected color is $SELECTED_COLOR"

      - name: Run nx command to show affected projects
        uses: gh640/command-result-action@v1
        with:
          command: npx nx show projects --affected -t build --base=${{ steps.setSHAs.outputs.base }} --head=${{ steps.setSHAs.outputs.head }}
        id: myaction

      - name: Affected string
        run: echo "Affected string ${{ steps.myaction.outputs.stdout }}"

      - name: Clean affected string
        run: echo "Affected string ${{ steps.myaction.outputs.stdout }}" | tr '\t\n' ' '

      - name: Set up matrix
        id: set_up_matrix
        run: |
          cleaned_output=$(echo "${{ steps.myaction.outputs.stdout }}" | tr '\t\n' ' ')

          IFS=' ' read -r -a words <<< "$cleaned_output"

          json_array="["
          for word in "${words[@]}"
          do
            json_array+="\"$word\","
          done
          json_array="${json_array%,}"
          json_array+="]"

          echo "::set-output name=project_list::$json_array"

      - name: Show project list
        run: echo "The project list is ${{ steps.set_up_matrix.outputs.project_list }}"

  build:
    needs: split_nx_projects
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    strategy:
      matrix:
        project: ${{fromJson(needs.split_nx_projects.outputs.project_list)}}
    concurrency:
      group: 'pages'
      # cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: npm install

      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        id: setSHAs
        uses: nrwl/nx-set-shas@v4

      - name: Run nx command with affected projects
        id: affected_projects
        run: |
          affected=$(npx nx show projects --affected -t build --base=${{ steps.setSHAs.outputs.base }} --head=${{ steps.setSHAs.outputs.head }})
          echo "::set-output name=projects::$affected"

      - name: Set affected projects
        run: |
          affected_projects="${{ steps.affected_projects.outputs.projects }}"
          echo "PROJECTS=$affected_projects" >> $GITHUB_ENV

      - name: Build affected projects
        run: npx nx affected -t build --base=${{ steps.setSHAs.outputs.base }} --head=${{ steps.setSHAs.outputs.head }}

      - name: Read project config
        id: read_project_config
        run: echo "::set-output name=config::$(cat projects-config.json)"

      - name: Process deploy steps
        id: process_deploy_steps
        run: |
          config=$(cat projects-config.json)
          for project in "${projects[@]}"; do
            repoLink=$(echo "$config" | jq -r ".projects[\"$project\"].repoLink")
            projectPath=$(echo "$config" | jq -r ".projects[\"$project\"].projectPath")
            echo "REPO_LINK=${repoLink}" >> $GITHUB_ENV
            echo "PROJECT_PATH=${projectPath}" >> $GITHUB_ENV
            echo "- name: Deploy $project"
            echo "  uses: peaceiris/actions-gh-pages@v3"
            echo "  with:"
            echo "    personal_token: ${{ secrets.KARMA_ORG }}"
            echo "    external_repository: ${{ env.REPO_LINK }}"
            echo "    publish_dir: ${{ env.PROJECT_PATH }}"
          done

      - name: Debug Deployment Step
        run: |
          echo "DEBUG: repoLink = ${{ env.REPO_LINK }}"
          echo "DEBUG: projectPath = ${{ env.PROJECT_PATH }}"

      - name: One more deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.KARMA_ORG }}
          external_repository: ${{ env.REPO_LINK }}
          publish_dir: ${{ env.PROJECT_PATH }}
