name: GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install
        run: npm install
      - name: Read Project Config
        run: cat projects-config.json
      - name: List current folder
        run: ls -la
      - name: Build app
        run: npx nx run-many --target=build --projects=e-auto-ladestation,hochwasser
      - name: List current folder
        run: ls -la
      - name: Get Affected Projects
        id: get_affected_projects
        run: |
          affected_projects=$(npx nx show projects --affected --base=main)
          projects_list=$(echo "$affected_projects" | awk '{print "\""$1"\""}' | paste -sd "," -)
          echo "::set-output name=projects::$projects_list"

      - name: Print Affected Projects
        run: |
          affected_projects="${{ steps.get_affected_projects.outputs.projects }}"
          echo "Affected Projects:"
          echo "$affected_projects"

      - name: Check for specific project
        id: check_project
        run: |
          affected_projects="${{ steps.get_affected_projects.outputs.projects }}"
          affected_projects=${affected_projects#"\""}
          affected_projects=${affected_projects%"\""}
          IFS=',' read -ra projects_array <<< "$affected_projects"
          for project in "${projects_array[@]}"; do
            if [ "$project" = "hochwasser" ]; then
              echo "hochwasser true"
              repo_link=$(jq -r '.projects.hochwasser.repo_link' projects-config.json)
              project_path=$(jq -r '.projects.hochwasser.project_path' projects-config.json)
              echo "repo_link: $repo_link"
              echo "project_path: $project_path"
              echo "::set-output name=deploy_required::true"
            fi
          done

      - name: Deploy on condition
        if: ${{ steps.check_project.outputs.deploy_required == 'true' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.KARMA_ORG }}
          external_repository: ${{ steps.check_project.outputs.repo_link }}
          publish_dir: ${{ steps.check_project.outputs.project_path }}

  #     Check for config file
  #    If no config file is here  cancel deployment.
  #   If there is a config file read the variables and save it to yml variables

  # - name: Deploy B
  #   uses: peaceiris/actions-gh-pages@v3
  #   # if: github.ref == 'refs/heads/main'
  #   with:
  #     personal_token: ${{ secrets.KARMA_ORG }}
  #     # github_token: ${{ secrets.KAMAFIRST }}
  #     # deploy_key: ${{ secrets.KAMAFIRST }}
  #     external_repository: carma-demo/topic-hochwasser
  #     publish_dir: ./dist/apps/topicmaps/hochwasser
