name: Deployment

# run-name: My Custom Run Name
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  workflow_dispatch:
    #   inputs:
    #         action-name:
    #           description: "Please enter a proper Action Name (Default=Deployment)"
    #           required: false
    inputs:
      deploy_target:
        description: 'Custom value'
        required: false

  push:
    branches:
      - main

jobs:
  split_nx_projects:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
