name: Deployment

run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      deploy_target:
        description: 'Custom value'
        required: false

  push:
    branches:
      - main

jobs:
  split_nx_projects:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Show input
        run: echo "Deploy to ${{ inputs.deploy_target }}"
